services:
  app-service:
    build: ./services/app
    container_name: app-service
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:V3NpdNKtc671fFsC@db.azunedrfyjxdvuszzsvp.supabase.co:5432/postgres
  user-service:
    build: ./services/users
    container_name: user-service
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://bmnaufaal:JWcwy46Myd352Vu1@ac-url9yul-shard-00-00.i2vm5c8.mongodb.net:27017,ac-url9yul-shard-00-01.i2vm5c8.mongodb.net:27017,ac-url9yul-shard-00-02.i2vm5c8.mongodb.net:27017/?ssl=true&replicaSet=atlas-uyjpn3-shard-0&authSource=admin&retryWrites=true&w=majority
  orchestrator:
    build: ./orchestrator
    container_name: orchestrator
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - APP_SERVICE_URL=http://app-service:4002
      - USER_SERVICE_URL=http://user-service:4001
      - PORT_REDIS=19472
      - HOST_REDIS=redis-19472.c289.us-west-1-2.ec2.cloud.redislabs.com
      - PASS_REDIS=K8QKmwWDwSnFMXE6RjoYJLvAAdng8cWk
