services:
  app-service:
    build: ./services/app
    container_name: app-service
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${SUPABASE_URL}
  user-service:
    build: ./services/users
    container_name: user-service
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - URL_MONGODB=${URL_MONGODB}
  orchestrator:
    build: ./orchestrator
    container_name: orchestrator
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - APP_SERVICE_URL=${APP_SERVICE_URL}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - PORT_REDIS = '19472'
      - HOST_REDIS = 'redis-19472.c289.us-west-1-2.ec2.cloud.redislabs.com'
      - PASS_REDIS = 'K8QKmwWDwSnFMXE6RjoYJLvAAdng8cWk'
